language: python

cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - pypy3
 - pypy
 - 2.7
 - 3.7-dev
 - 3.6
 - 3.5
 - 3.4

sudo: false

install:
 - pip install pycodestyle pyflakes
 - pip install pillow
 - pip install coverage

script:
 - pip install -e .
 - coverage erase
 - travis_retry coverage run --append --include="src/*" test/unit/test_manager.py
 - travis_retry coverage run --append --include="src/*" test/functional/test_manager.py

 # Static analysis
 - pyflakes setup.py src test
 - pycodestyle --statistics --count setup.py src test

after_success:
 - coverage report
 - pip install codecov
 - codecov

matrix:
  fast_finish: true
