language: python

cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - pypy3
 - 3.7-dev
 - 3.6
 - 3.5
 - 3.4

sudo: false

install:
 - pip install -U pycodestyle pyflakes
 - pip install -U pillow
 - pip install -U coverage
 # Test at least one version with tqdm
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U tqdm; fi

script:
 - pip install -e .
 - coverage erase
 - travis_retry coverage run --append --include="src/*" test/unit/test_manager.py
 - travis_retry coverage run --append --include="src/*" test/functional/test_manager.py

 # Static analysis
 - pyflakes setup.py src test
 - pycodestyle --statistics --count setup.py src test

after_success:
 - coverage report
 - pip install codecov
 - codecov

matrix:
  fast_finish: true
