language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: "pypy3"
    - python: '3.7'
      dist: xenial
    - python: '3.6'
    - python: '3.5'

install:
 - pip install -U coverage
 - pip install -U flake8
 - pip install -U pillow
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U black; fi
 # Test at least one version with tqdm
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U tqdm; fi

script:
 - pip install -e .
 - python setup.py --version
 - coverage erase
 - travis_retry coverage run --append --include="src/*" test/unit/test_manager.py
 - travis_retry coverage run --append --include="src/*" test/functional/test_manager.py

 # Static analysis
 - flake8 setup.py src test examples
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff setup.py src test examples; fi

after_success:
 - coverage report
 - pip install -U codecov
 - codecov

deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    on:
      tags: false
      repo: hugovk/osmviz
      branch: master
      python: 3.7
    user: hugovk
    password:
        secure: "SRpqE989FOEwU1i/eRmxTAgcVgtUh5SZ5fy3suJPZURi3VCjT4UCGLnC5TccCtF2buJOsy5rj+ksOU242WZeZKLmQAbEV8AroZjJ8JtoV5Kztn4PPE7lEE73vUKS9bLFg1vHqH6CV4C+QY95bKj86QpFk5wVkF3zODbKyE2Cg/U="
    distributions: sdist --format=gztar bdist_wheel
    skip_existing: true
  - provider: pypi
    on:
      tags: true
      repo: hugovk/osmviz
      branch: master
      python: 3.7
    user: hugovk
    password:
        secure: "SRpqE989FOEwU1i/eRmxTAgcVgtUh5SZ5fy3suJPZURi3VCjT4UCGLnC5TccCtF2buJOsy5rj+ksOU242WZeZKLmQAbEV8AroZjJ8JtoV5Kztn4PPE7lEE73vUKS9bLFg1vHqH6CV4C+QY95bKj86QpFk5wVkF3zODbKyE2Cg/U="
    distributions: sdist --format=gztar bdist_wheel
    skip_existing: true
