language: python

python:
  - pypy
  - pypy3
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:
  - sudo apt-get build-dep python-pygame
  - pip install pygame
  - pip install pillow

script:
  - cd test
  - ./test.sh

after_success:
  - pip install pep8 pyflakes
  - pep8 --statistics --count .
  - pyflakes . | tee >(wc -l)

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
    - python: 2.6
    - python: 3.2
    - python: 3.3
    - python: 3.4
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4


  fast_finish: true
